import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import critical from 'rollup-plugin-critical'

// Optional: to detect GitHub Pages if needed
const isGithubPages = process.env.NODE_ENV === 'production';

export default defineConfig({
  plugins: [
    react(),
    // ⬇️ Add the critical CSS plugin only in production
    isGithubPages &&
      critical({
        criticalBase: 'dist/', // folder generated by `vite build`
        criticalUrl: '',       // base URL, leave '' for local
        criticalPages: [
          { uri: '', template: 'index.html' }, // critical CSS for homepage
        ],
        inline: true,
        width: 1300,
        height: 900,
      }),
  ].filter(Boolean), // remove false values (if isGithubPages is false)

  base: '/', // for Vercel or root domain; change to '/repo-name/' for GitHub Pages

  build: {
    rollupOptions: {
      output: {
        manualChunks: undefined, // Avoids JS chunking that can confuse critical
      },
    },
  },
})